### ISSUE TITLE
Запросы к БД

### ISSUE THREAD

**Issue by tretyakovpe** [ncedu-tlt/cloudbox#2]
- \- получить список файлов по айди юзера
- \- удалить файл по айди, 
- удалить файлы по набору айди, 
- \- получить все удаленные файлы по айди юзера
- \- изменить права (роли пользователя), 
- получить пользователей по типу юзер, 
- получить пользователей по типу модератор, так же и по типу юзер и по типу модератор, 
- создание пользователя со всеми его ролями, 
- найти файл по имени(это можно и в клиенте делать, но надо и в бд предусмотреть), 
- \- найти файлы по расширению. 
- \- получить список пользователей,кому доступен этот файл

там где поиск по названию , конечно без учета регистра,

**Comment by avtronev** [comment]
удалить файл по айди, 
удалить файлы по набору айди, 

Это одно и то-же. По сути должен быть запрос принимающий на вход коллекцию ID а сколько их там, один или несколько - не важно. Так-же не следует забывать, что удалять надо файлы и физически, с диска.
